name: "aws-serverless-deploy"
description: "Deploy Lambda functions to AWS using Serverless framework"
author: mirceapreotu
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: green